### PR TITLE
Added Lookup3From2

### PR DESCRIPTION
**Pull request by julian-burger-ttd**
Added Lookup3From2 function to efficiently lookup the 3-character code from a two-character code.

### CODE REVIEW

**Comment by julian-burger-ttd** [comment]
@peterdonald3 please review and comment. Thanks.

**Comment by peterdonald3** [comment]
@julian-burger-ttd this package is actually a mirror from my Gitlab repo.  Thanks for the suggestion/MR, I've added three new functions and tests in Gitlab following your recommendation. They can be found here: https://github.com/taxedio/iso3166/blob/main/rawchecks.go

**Comment by julian-burger-ttd** [comment]
Thanks, Peter! One minor comment about the `RawAlpha2Match` comment 
```
// Check map for Alpha3 Match and returns Alpha3 code as string
```
Should be `... returns Alpha2 ...`

**Comment by peterdonald3** [comment]
@julian-burger-ttd cheers for the heads up. I've updated and tagged as v0.5.0. I will be rewriting the docs/descs in future before v1.0.0

...Just realised it's still a bit misleading. I'll create a ticket to update all descs and look at it this weekend hopefully.

**Pull request closed without merging**
